name: circuit_simulator_full
description: Full Project Skeleton - Workbench-style circuit simulator (Flutter).
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/