name: circuitsim
description: CircuitSim - Workbench-style circuit simulator (Flutter) - Arabic RTL MVP
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^3.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/